spring:
  application:
    name: xlei-ai-agent
# 为保护账号的安全性,隐私配置写在 application-local.yml(不提交)
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://PgSQL实例的公网地址/xlei_ai_agent
    username: 用户名
    password: 密码
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    dashscope:
      api-key: Your API KEY
      chat:
        options:
          model: qwen-plus

    # 临时注释掉，便于大家开发调试和部署
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
# searchAPI
search-api:
  api-key: Your API KEY
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xlei.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG

